BoxLayout:
    orientation: "horizontal"

    Splitter:
        sizable_from: "right"
        min_size: self.strip_size + 1
        max_size: self.parent.width

        BoxLayout:
            orientation: "vertical"
            VolumeSlider:
                min: 0
                max: 1
                size_hint_y: None
            PlotSwitch:
                text: "Plot"
                size_hint_y: None
            Plot:
                opacity: 1 if self.active else .1

    Avatar:
